server:
  # 测试用端口号
  port: 8081
  servlet:
    # 测试时的上下文根
    context-path: /core

spring:
  # 数据库配置
  datasource:
    # 数据库驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库地址
    url: jdbc:mysql://127.0.0.1:3306/haiyuan?allowMultiQueries=true
    # 数据库用户名
    username: root
    # 数据库密码
    password: MyMemory19910516
    dbcp2:
      # 初始连接数
      initial-size: 10
      # 最大连接数
      max-total: 100
      # 最大空闲
      max-idle: 25
      # 最小空闲
      min-idle: 15
      # 最长等待事件
      max-wait-millis: 2000

# Mybatis-Plus 配置
mybatis-plus:
  # 指定Mybatis的mapper文件
  mapper-locations: classpath:mybatis/**.xml
  # 日志输出实现类
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info