server:
  # 测试用端口号
  port: 8081
  servlet:
    # 测试时的上下文根
    context-path: /core
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat.uri-encoding: UTF-8

spring:
  # 数据库配置
  datasource:
    dump-path: /Users/haiyuan/Desktop/dump
    # 数据库驱动类
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    # 数据库地址
    #url: jdbc:sqlserver://127.0.0.1:1433;databaseName=gqys;
    url: jdbc:mysql://127.0.0.1:3306/suxch?allowMultiQueries=true&rewriteBatchedStatements=true
    #url: jdbc:oracle:thin:@172.172.103.229:1521:orcl2
    # 数据库用户名
    username: root
    # 数据库密码
    password: MyMemory19910516
    # 数据库连接池配置
    dbcp2:
      # 初始连接数
      initial-size: 10
      # 最大连接数
      max-total: 100
      # 最大空闲
      max-idle: 25
      # 最小空闲
      min-idle: 15
      # 最长等待事件
      max-wait-millis: 2000

#decorator:
#  datasource:
#    p6spy:
#      #日志格式
#      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
#      #自定义日志类
#      logging: custom
#      custom-appender-class: com.example.testinit.config.StdoutLogger

# Mybatis-Plus 配置
mybatis-plus:
  # 指定Mybatis的mapper文件
  mapper-locations: classpath:mybatis/**.xml
  # 日志输出实现类
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 枚举转换方式 (注意增加注解@EnumValue)
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

logging:
  level:
    root: info
knife4j:
  enable: true
  openapi:
    title: 彩票管理接口
    description: "彩票管理接口"
    email: mymemory0607@vip.qq.com
    concat: 苏希辰
    url: https://www.mymemory.com.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - cn.com.blueInfo
