business:
  lottery:
    # 体育彩票
    sports:
      url: https://webapi.sporttery.cn/gateway/lottery/getHistoryPageListV1.qry
      method: get
      query:
        - pageNo=1
        - pageSize=30
        - gameNo=85
        - provinceId=0
        - isVerify=1
      header:
        - authority:webapi.sporttery.cn
        - method:GET
        - path:/gateway/lottery/getHistoryPageListV1.qry?gameNo=85&provinceId=0&pageSize=30&isVerify=1&pageNo=56
        - scheme:https
        - accept:application/json, text/javascript, */*; q=0.01
        - accept-encoding:gzip, deflate, br, zstd
        - accept-language:zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
        - origin:https://static.sporttery.cn
        - priority:u=1, i
        - referer:https://static.sporttery.cn/
        - sec-ch-ua:"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"
        - sec-ch-ua-mobile:?0
        - sec-ch-ua-platform:"Windows"
        - sec-fetch-dest:empty
        - sec-fetch-mode:cors
        - sec-fetch-site:same-site
        - user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0

    welfare:
      url: https://www.cwl.gov.cn/cwl_admin/front/cwlkj/search/kjxx/findDrawNotice
      method: get
      query:
        - pageNo=1
        - pageSize=30
        - name=ssq
        - issueCount=
        - issueStart=
        - issueEnd=
        - dayStart=
        - dayEnd=
        - week=
        - systemType=PC
      header:
        - Accept:application/json, text/javascript, */*; q=0.01
        - Accept-Encoding:gzip, deflate, br, zstd
        - Accept-Language:zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
        - Connection:keep-alive
        - Cookie:HMF_CI=169cc65231d1db36b4a1dd160492dece08f52b2b163448aa2a4152603cf2fd615f0281826f28943d0c806eec0ba90510f8649eabd6fc65a3f7816b44aecb8b270e; 21_vq=1
        - Host:www.cwl.gov.cn
        - Referer:https://www.cwl.gov.cn/ygkj/wqkjgg/ssq/
        - Sec-Fetch-Dest:empty
        - Sec-Fetch-Mode:cors
        - Sec-Fetch-Site:same-origin
        - User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
        - X-Requested-With:XMLHttpRequest
        - sec-ch-ua:"Chromium";v="130", "Microsoft Edge";v="130", "Not?A_Brand";v="99"
        - sec-ch-ua-mobile:?0
        - sec-ch-ua-platform:"Windows"